### ISSUE TITLE
Frequent GUI crashes

### ISSUE THREAD

**Issue by KCallaghan** [CentreForHydrology/WDPM#2]
With the error message: 

> Gdk-Message: 22:39:47.991: WDPM.py: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.

This happens when I click 'start', but only sometimes with a given set of parameters. 

openjournals/joss-reviews#2276

**Comment by KevinShook** [comment]
I'll pass this along to the rest of the team

**Comment by KevinShook** [comment]
The GUI issues appear to have been caused by a change in Python.
The code has not been touched in several years, and most of
the users never use the GUI, so it was missed.
Apparently there was a change from Python, which required
changing all of the instances of  `wx.OPEN`  to `wx.FD_OPEN`.
This has now been done, and the GUI now appears to run properly

**Comment by r-barnes** [comment]
If the GUI isn't widely used, you could reconsider whether it's worth having. I don't have a strong stance on this one way or the other.

**Comment by KevinShook** [comment]
The GUI has been updated to use Python 3 and now works properly. The program can be run with or without the GUI as explained in the manual.
