### ISSUE TITLE
Authorship

### ISSUE THREAD

**Issue by awickert** [CentreForHydrology/WDPM#30]
You write in the acknowledgments that, "Much of the OpenCL code and the Python GUI were written by Oluwaseun Sharomi." I am glad that you have acknowledged Sharomi's contributions. However, the OpenCL code and Python GUI are key pieces of what you are publishing here. I do not see Sharomi's name in the references for any work that they may have previously published, which could have been a reason to just cite their work as a basis for what you are presenting here. Therefore, it would seem that Sharomi's work is being published for the first time here without their direct participation. I find this concerning.

Could you justify your rationale for your provided author list and/or consider expanding it in a way that would seem to give more appropriate credit to contributors?

**Comment by KevinShook** [comment]
This is a very good question. We have been trying to contact Oluwaseun Sharomi with no success. He left Canada several years ago and is apparently in Abu Dhabi, but has not responded to any of our emails

**Comment by awickert** [comment]
I see. That is a difficult situation; I imagine that you are a bit stuck between wanting to include him for the work and not wanting to do something without his permission. I think that this might be something important to check with JOSS.

**Comment by kbarnhart** [comment]
This is a good question. I will ask the joss editorial board an let you know what they say. 

openjournals/joss-reviews#2276

**Comment by kbarnhart** [comment]
Did not need to contact the rest of the editorial board as I found the answer by looking carefully at the [JOSS authorship guidelines](https://joss.readthedocs.io/en/latest/submitting.html?highlight=authorship#authorship). 

I come to the conclusion that Oluwaseun Sharomi would need to consent to being an author in order to be listed as an author on a JOSS paper. 

Key sentence (emphasis added): The authors themselves assume responsibility for deciding who should be credited with co-authorship, and **co-authors must always agree to be listed.**

It sounds as if you followed an appropriate course in this circumstance: namely attempting to contact him for his consent, and in the present circumstance of not being able to make contact, acknowledging him for his contributions. 

Let me know if you have any questions or clarifications.

**Comment by KevinShook** [comment]
Thank you - this was what I had thought, that it wouldn't be right to put his name on the paper without his consent.

**Comment by r-barnes** [comment]
This is an unfortunate situation. Perhaps the acknowledgements could clarify what's happened so that eventual readers, including Oluwaseun themself, don't end up with the same question as @awickert?

**Comment by awickert** [comment]
I agree with @r-barnes that clarification in the acknowledgments would be good. Once @KevinShook can confirm this (or another compatible solution), I will close this Issue.

**Comment by awickert** [comment]
Based on this,
"Much of the OpenCL code and the first version of the Python GUI were written by Oluwaseun Sharomi. Unfortunately, despite many attempts, we have been unable to contact Dr. Sharomi, so cannot give him co-authorship of this paper."
I am closing the Issue. Thank you.
