### ISSUE TITLE
Can we unpackage the manual?

### ISSUE THREAD

**Issue by r-barnes** [CentreForHydrology/WDPM#58]
Having vital information tucked away in a PDF file doesn't seem like a good idea to me.
* It makes the information harder to search both from the web, from the CLI, and from within an IDE.
* It makes it more challenging to version control
* The TeX format can be unintuitive to some and you're not making use of most of its powerful features (e.g., equation typesetting, extensive cross-referencing) here, so I don't see a compelling reason to use it for those.
* It means that a user looking at your software immediately has to start digging to even figure out how to use it. Presenting more information on the README page would be a nicer first experience.
* Even the README page doesn't actually provide a hyperlink to the manual.

I would feel more comfortable if you were to translate the manual into markdown format. That makes it easy to read on Github, easy to version control, and still human-readable in any standard code editor.

A few links to people arguing against PDFS:
https://www.theguardian.com/higher-education-network/2015/feb/11/researchers-its-time-to-ditch-the-pdf

https://www.nngroup.com/articles/pdf-unfit-for-human-consumption/

https://blog.scholasticahq.com/post/why-pdfs-no-longer-enough-file-types-digital-journals/

https://www.theatlantic.com/science/archive/2018/04/the-scientific-paper-is-obsolete/556676/?single_page=true

**Comment by KevinShook** [comment]
The manual was written in Lyx (not TeX) because it was easiest for all of the authors, 
not all of whom are comfortable with markdown. It could be converted to markdown, 
although this would take some work.
The Lyx file does work with git, as it is uncompressed, although it is much less easily 
read by humans than a markdown file.

I had looked at converting the manual to markdown, but there are some disadvantages.
Markdown does not provide an easy way to generate a table of contents,
which makes the rather long manual more usable, nor does it handle cross-references,
which are present in the document. Unless I use Rmarkdown, there is no automatic citation/bibliography
handling, which is also required. 

Given the complexities of building the program, requiring the installation of other software 
the user will have to read the manual before getting the program to work.
Even if markdown is used, it will need to be rendered to make it fully readable by the users,
which will mean outputting to html, or pdf file, anyway. 

The README file does indicate the purpose of the program, as well the
software that will need to be installed, but adding a link to the manual is
a good idea, so that potential users can get a better understanding of the 
program before downloading it.

**Comment by KevinShook** [comment]
The README file now includes a link to the manual

Commit 9d37dfd

**Comment by r-barnes** [comment]
I still think presenting documentation this way is a poor idea, but since JOSS doesn't otherwise object I'm closing the issue.
